06-02-2022, 10:39:51, 1654166391681, Action: test_1_selenium_customer_share_request_with_customer, Error: jsm_webdriver = <selenium.webdriver.chrome.webdriver.WebDriver (session="002af497e154079fa705820e97daad19")>
jsm_datasets = {'agents': [['performance_agent_0_aaoqafelvunpurt', 'password'], ['performance_agent_0_aavvzgunepcmlzo', 'password'], ...dzqft', 'password'], ...], 'custom_issues': [], 'customer_password': 'password', 'customer_request_id': '1049331', ...}
jsm_screen_shots = None

    def test_1_selenium_customer_share_request_with_customer(jsm_webdriver, jsm_datasets, jsm_screen_shots):
>       modules_customers.share_request_with_customer(jsm_webdriver, jsm_datasets)

selenium_ui/jsm_ui_customers.py:29: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
selenium_ui/jsm/modules_customers.py:167: in share_request_with_customer
    measure()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

    @functools.wraps(func)
    def wrapper():
        if LOGIN_ACTION_NAME in interaction:
            globals.login_failed = False
        if globals.login_failed:
            pytest.skip(f"login is failed")
        start = time.time()
        error_msg = 'Success'
        full_exception = ''
        try:
            func()
            success = True
        except Exception:
            success = False
            # https://docs.python.org/2/library/sys.html#sys.exc_info
            exc_type, full_exception = sys.exc_info()[:2]
            error_msg = f"Failed measure: {interaction} - {exc_type.__name__}"
        end = time.time()
        timing = str(int((end - start) * 1000))
    
        lockfile = f'{selenium_results_file}.lock'
    
        with filelock.SoftFileLock(lockfile):
            with open(selenium_results_file, "a+") as jtl_file:
                timestamp = round(time.time() * 1000)
                jtl_file.write(f"{timestamp},{timing},{interaction},,{error_msg},,{success},0,0,0,0,,0\n")
    
        print(f"{timestamp},{timing},{interaction},{error_msg},{success}")
    
        if not success:
            if LOGIN_ACTION_NAME in interaction:
                globals.login_failed = True
>           raise Exception(error_msg, full_exception)
E           Exception: ('Failed measure: selenium_customer_share_request_with_customer - Exception', Exception('Failed measure: selenium_customer_share_request:share_request_with_customer - TimeoutException', TimeoutException('Error in wait_until: Timed out after 20 sec waiting for <function visibility_of_element_located.<locals>._predicate at 0x7f131d347310>. \nLocator: (\'xpath\', "//button[contains(text(),\'Share\')]")', None, ['#0 0x55dc8719f533 <unknown>', '#1 0x55dc86efe1e8 <unknown>', '#2 0x55dc86f342d7 <unknown>', '#3 0x55dc86f344a1 <unknown>', '#4 0x55dc86f67494 <unknown>', '#5 0x55dc86f51f6d <unknown>', '#6 0x55dc86f65224 <unknown>', '#7 0x55dc86f51e33 <unknown>', '#8 0x55dc86f2771a <unknown>', '#9 0x55dc86f28875 <unknown>', '#10 0x55dc871e3e1d <unknown>', '#11 0x55dc871e7751 <unknown>', '#12 0x55dc871ce07e <unknown>', '#13 0x55dc871e8388 <unknown>', '#14 0x55dc871c2fe0 <unknown>', '#15 0x55dc87204748 <unknown>', '#16 0x55dc872048c8 <unknown>', '#17 0x55dc8721e70d <unknown>', '#18 0x7f01e3e00609 <unknown>', ''])))

selenium_ui/conftest.py:157: Exception
06-02-2022, 10:49:39, 1654166979025, Action: test_1_selenium_customer_share_request_with_customer, Error: jsm_webdriver = <selenium.webdriver.chrome.webdriver.WebDriver (session="002af497e154079fa705820e97daad19")>
jsm_datasets = {'agents': [['performance_agent_0_aaoqafelvunpurt', 'password'], ['performance_agent_0_aavvzgunepcmlzo', 'password'], ...dzqft', 'password'], ...], 'custom_issues': [], 'customer_password': 'password', 'customer_request_id': '1049331', ...}
jsm_screen_shots = None

    def test_1_selenium_customer_share_request_with_customer(jsm_webdriver, jsm_datasets, jsm_screen_shots):
>       modules_customers.share_request_with_customer(jsm_webdriver, jsm_datasets)

selenium_ui/jsm_ui_customers.py:29: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
selenium_ui/jsm/modules_customers.py:167: in share_request_with_customer
    measure()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

    @functools.wraps(func)
    def wrapper():
        if LOGIN_ACTION_NAME in interaction:
            globals.login_failed = False
        if globals.login_failed:
            pytest.skip(f"login is failed")
        start = time.time()
        error_msg = 'Success'
        full_exception = ''
        try:
            func()
            success = True
        except Exception:
            success = False
            # https://docs.python.org/2/library/sys.html#sys.exc_info
            exc_type, full_exception = sys.exc_info()[:2]
            error_msg = f"Failed measure: {interaction} - {exc_type.__name__}"
        end = time.time()
        timing = str(int((end - start) * 1000))
    
        lockfile = f'{selenium_results_file}.lock'
    
        with filelock.SoftFileLock(lockfile):
            with open(selenium_results_file, "a+") as jtl_file:
                timestamp = round(time.time() * 1000)
                jtl_file.write(f"{timestamp},{timing},{interaction},,{error_msg},,{success},0,0,0,0,,0\n")
    
        print(f"{timestamp},{timing},{interaction},{error_msg},{success}")
    
        if not success:
            if LOGIN_ACTION_NAME in interaction:
                globals.login_failed = True
>           raise Exception(error_msg, full_exception)
E           Exception: ('Failed measure: selenium_customer_share_request_with_customer - Exception', Exception('Failed measure: selenium_customer_share_request:share_request_with_customer - TimeoutException', TimeoutException('Error in wait_until: Timed out after 20 sec waiting for <function visibility_of_element_located.<locals>._predicate at 0x7f131ce74280>. \nLocator: (\'xpath\', "//button[contains(text(),\'Share\')]")', None, ['#0 0x55dc8719f533 <unknown>', '#1 0x55dc86efe1e8 <unknown>', '#2 0x55dc86f342d7 <unknown>', '#3 0x55dc86f344a1 <unknown>', '#4 0x55dc86f67494 <unknown>', '#5 0x55dc86f51f6d <unknown>', '#6 0x55dc86f65224 <unknown>', '#7 0x55dc86f51e33 <unknown>', '#8 0x55dc86f2771a <unknown>', '#9 0x55dc86f28875 <unknown>', '#10 0x55dc871e3e1d <unknown>', '#11 0x55dc871e7751 <unknown>', '#12 0x55dc871ce07e <unknown>', '#13 0x55dc871e8388 <unknown>', '#14 0x55dc871c2fe0 <unknown>', '#15 0x55dc87204748 <unknown>', '#16 0x55dc872048c8 <unknown>', '#17 0x55dc8721e70d <unknown>', '#18 0x7f01e3e00609 <unknown>', ''])))

selenium_ui/conftest.py:157: Exception
